name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- script: dotnet restore
  displayName: dotnet restore

- script: dotnet build -c Release
  displayName: dotnet build

- script: dotnet test -c Release --no-build --logger trx
  displayName: dotnet test
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet pack -c Release --no-build --version-suffix ci-$BUILD_BUILDNUMBER
  displayName: dotnet pack
